[project]
name = "mcp-finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "tabulate>=0.9.0",
]
